### ISSUE TITLE
The code doesn't work

### ISSUE THREAD

**Issue by noideaw** [neochapay/QtInstagram#5]
I wrote these lines of code in main.cpp:
```
int main()
{
    Instagram* me = new Instagram();
    me->setUsername("no_ideaw");
    me->setPassword("SOME_PASSWORD");
    me->login();
    me->getProfileData();
    return 0;
}
```
Then I ran it and this all of the output showing on terminal:

> Press <RETURN> to close this window...

It even didn't return an empty string for `me->getProfileData();` which means the object didn't work!
What is wrong about that?

**Comment by neochapay** [comment]
It`s Qt application you must use Qt Signal-Slot model after login you suld wait signal profileConnected(QVariant) after you cat do me->getProfileData(); and wait signal profileDataReady(QVariant);
